### ISSUE TITLE
Error：dreampi2.py

### ISSUE THREAD

**Issue by ngc20108** [Ryochan7/dreampi2-custom#1]
Error·
kige@dreampie:~$ sudo ./dreampi2.py
Traceback (most recent call last):
  File "./dreampi2.py", line 3, in <module>
    import serial
ImportError: No module named serial

--------------------------1-----------------------------
[   11.070133] shpchp: Standard Hot Plug PCI Controller Driver version: 0.4
[   11.086677] cdc_acm 2-2:1.0: ttyACM0: USB ACM device
[   11.094529] usbcore: registered new interface driver cdc_acm
[   11.094540] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters

---------------------------2----------------------------------
kige@dreampie:~$ sudo dmesg | grep tty
[    0.000000] console [tty0] enabled
[   11.086677] cdc_acm 2-2:1.0: ttyACM0: USB ACM device
----------------------------3---------------------------------

MODEM_DEVICE = "ttyACM0"

**Comment by Ryochan7** [comment]
The serial module is available from the python-serial package on Ubuntu. It is also available from pip under the name pyserial.

```
sudo apt-get install python-serial
```

https://pypi.org/project/pyserial/

**Comment by ngc20108** [comment]
> 串行模块可以从Ubuntu上的python-serial包获得。它也可以从名为pyserial的pip获得。
> 
> ```
> sudo apt-get install python-serial
> ```
> https://pypi.org/project/pyserial/

Thank you. I have found and dealt with this problem. It has run normally.

**Comment by ngc20108** [comment]
> > 串行模块可以从Ubuntu上的python-serial包获得。它也可以从名为pyserial的pip获得。
> > ```
> > sudo apt-get install python-serial
> > ```
> > https://pypi.org/project/pyserial/
> 
> Thank you. I have found and dealt with this problem. It has run normally.

Can it specify dns, but can't establish a connection on GameCube modem, Dreamcast is all right, raspberry PI uses 0.47 uf, 220 ohm, and works fine

**Comment by Ryochan7** [comment]
I wouldn't know anything about the specifics to getting the GameCube online with the modem. As for dns, you would have to edit your PPP options file in order to change the DNS server that is used. The file included in this repo points to the DreamPi DNS server which should work just fine for connecting to Dreamcast game servers and the web. You would likely need to change the address used for **ms-dns** to play any type of GameCube games online.

https://github.com/Ryochan7/dreampi2-custom/blob/master/example-files/ppp/options#L8
